import Navbar from '@/components/Navbar'
import { TasksProvider } from '@/context/TasksContext'
import { Toaster } from 'react-hot-toast'
import { Layout } from '@/components/Layout'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TasksProvider>
          <Navbar />
          <Layout>{children}</Layout>
          <Toaster />
        </TasksProvider>
      </body>
    </html>
  )
}
